name: github-pages

on:
  # schedule:
  #   - cron: '0 7 * * 1-4'
    
#   schedule:
#     # https://cron.help/#0/30_*_*_*_*
#     - cron: '0 6 * * *'
  push:
    branches: 
    - app/dev

  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #   branches:
  #     - master
  #   paths:
  # TRIGGER only on pull request that changes these file-paths... 
  # 
  #     - "src/db.py
  #     - "src/requirements.txt"
  #     - "src/docs/conf.py"
  #     - "src/docs/Makefile"
  #     - "src/docs/_static/styles.css"
  #     - "src/docs/_static/intel.css"
  #     - "src/docs/_static/assets/logo-energyblue-white.svg"
  #     - "src/docs/_templates/script.js"
  #     - "src/docs/_templates/base.html"
  #     - "src/docs/_templates/index.html"

# defaults:
#   run:
#     working-directory: src

jobs:
  pages:
    name: Build GitHub Pages
    runs-on: ubuntu-latest 

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - run: find | sort 

    - uses: actions/checkout@v3 
      # with:
        # path: app/dev 

    - uses: actions/checkout@v3
      name: Check out master
      with: 
        ref: 'refs/heads/master'
        path: master
        # path: '${{ github.workspace }}/master'
        
  
    # TODO: mv 'python3 app/dev/src/db.py master'
    - name: Build JSON DB
      run: |
        python3 -m pip install -r src/requirements.txt
        echo master
        python3 src/db.py master

    # 
    - name: Remove JSON pre-prod  
      run: |       
        rm -rf src/docs/sample_db_pre.json

    - name: Build Sphinx
      run: |
        python3 -m pip install -r src/requirements.txt        
        python3 -m sphinx -W -b html src/docs/ src/docs/_build/
        echo $PWD
        echo ${{ github.ref }}

    - name: Add GPU-Occupancy-Calculator
      env: 
        GPU_OCC_CALC: src/docs/_build/Tools/GPU-Occupancy-Calculator/
      run: |
        mkdir -p ${GPU_OCC_CALC}   
        cd ${GPU_OCC_CALC}
        wget https://raw.githubusercontent.com/oneapi-src/oneAPI-samples/master/Tools/GPU-Occupancy-Calculator/index.html

    - name: Push docs
      if: ${{ github.ref == 'refs/heads/app/dev' }}
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPO: ${{ github.repository }} 
      run: |
        cd src/docs/_build/
        touch .nojekyll       
        git init
        git remote add origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}"
        git add -A
        git status
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -sm "$(date)"
        git branch -M gh-pages
        git push -u origin -f gh-pages
